In [2]:
import pandas as pd

In [3]:
df=pd.read_csv('uncleaned_appliances.csv')

In [4]:
df.head(10)

,goods-title-link--jump,goods-title-link--jump href,rank-title,rank-sub,price,discount,selling_proposition,goods-title-link
0,1pc Rechargeable Deep Tissue Muscle Handheld M...,https://us.shein.com/1pc-Rechargeable-Deep-Tis...,#1 Best Sellers,in Give Gifts,$2.03,-22%,NaN,NaN
1,1pc Portable Hanging Neck Fan,https://us.shein.com/1pc-Portable-Hanging-Neck...,#4 Best Sellers,in Top rated in Portable Fans,$6.48,-20%,NaN,NaN
2,1pc Pink Colored Curved Eyelash Curler False E...,https://us.shein.com/1pc-Pink-Colored-Curved-E...,NaN,NaN,$1.80,NaN,400+ sold recently,NaN
3,1 Mini Portable Handheld Fan With 2 Aa Batteri...,https://us.shein.com/1-Mini-Portable-Handheld-...,NaN,NaN,$0.88,-72%,5.6k+ sold recently,NaN
4,"Wit Water Flosser,Portable Oral Irrigator With...",https://us.shein.com/Wit-Water-Flosser-Portabl...,#6 Best Sellers,in Oral Irrigators,$12.06,-40%,NaN,NaN
5,"1pc Ice Pop Mold, Plastic Ice Cream Mold, Froz...",https://us.shein.com/1pc-Ice-Pop-Mold-Plastic-...,#10 Best Sellers,in Refrigerators & Freezers,$2.70,NaN,NaN,NaN
6,"Mini Pocket Bluetooth Thermal Printer, Portabl...",https://us.shein.com/Mini-Pocket-Bluetooth-The...,#8 Best Sellers,in Other Household Appliances,$3.50,NaN,NaN,NaN
7,1 PC 400ML Classic Ultra-Silent Air Humidifier...,https://us.shein.com/1-PC-400ML-Classic-Ultra-...,NaN,NaN,$4.90,NaN,NaN,NaN
8,6 Modes Multi-Functional Sonic Electric Toothb...,https://us.shein.com/6-Modes-Multi-Functional-...,#6 Best Sellers,in Oral Care Appliances,$4.28,-41%,NaN,NaN
9,1pc AA Battery Operated Portable Handheld Mini...,https://us.shein.com/1pc-AA-Battery-Operated-P...,#9 Best Sellers,in Household Appliances,$2.76,-5%,NaN,NaN

In [5]:
df.isnull().sum()

goods-title-link--jump         3946
goods-title-link--jump href    3946
rank-title                     3427
rank-sub                       3427
price                             0
discount                       1527
selling_proposition            2625
goods-title-link                 40
dtype: int64

In [6]:
df.shape

(3986, 8)

In [7]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 3986 entries, 0 to 3985
Data columns (total 8 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   goods-title-link--jump       40 non-null     str
 1   goods-title-link--jump href  40 non-null     str
 2   rank-title                   559 non-null    str
 3   rank-sub                     559 non-null    str
 4   price                        3986 non-null   str
 5   discount                     2459 non-null   str
 6   selling_proposition          1361 non-null   str
 7   goods-title-link             3946 non-null   str
dtypes: str(8)
memory usage: 885.9 KB

In [8]:
df['goods-title-link'].isnull().sum()

np.int64(40)

In [9]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 3986 entries, 0 to 3985
Data columns (total 8 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   goods-title-link--jump       40 non-null     str
 1   goods-title-link--jump href  40 non-null     str
 2   rank-title                   559 non-null    str
 3   rank-sub                     559 non-null    str
 4   price                        3986 non-null   str
 5   discount                     2459 non-null   str
 6   selling_proposition          1361 non-null   str
 7   goods-title-link             3946 non-null   str
dtypes: str(8)
memory usage: 885.9 KB

In [10]:
df['goods-title-link'].unique()

<ArrowStringArray>
[                                                                                                                                                                                                                                                   nan,
                                                                                            '4pcs Makeup Sponge Beauty Egg Set - Makeup Sponge For Foundation Blending With Egg Holder, Perfectly Used For Cream, Powder, Blush, Concealer, And Liquid',
                                                                                                                 '1pc Salon Tools Black Pink Universal Silicone Hair Dryer Diffuser Hood Adjustable Temperature Dispersion Resistant Drying Hair Dryer',
                                                                                                                                                                                    'Portable Lithium Battery Powered Hair Trimmer & Nose Hair Trimmer',
                                                                                                                        'Multifunctional Manual Food Chopper, Kitchen Vegetable Fruit Onion Garlic Nuts Herb Slicer, Hand-Powered Mixing Cutter, Green',
                                                                                                     '1 Set Of 2 Portable Fan Cleaning Brushes, Household Multi-Purpose Keyboard And Gap Cleaning Small Brush - Deep Into The Gap, Easily Remove Dust.',
 'Smart Electric Toothbrush With 6 Modes 42000vpm & Smart Timer - Effectively Cleans Teeth & Gums, Rechargeable USB Electric Toothbrush With 4/8 Replacement Head, Electric Toothbrush For Adults, Available In 3 Colors, Great Gift Father's Day Gift',
                                                                                                                                                                     '1pc 12.7cm Aluminum Metal Electric Battery Type Eyebrow Shaver Nose Hair Trimmer',
                                                                   'Professional Curler, Electrically Heated Automatic Curler, Negative Ion Electric Clip Curler, Portable Heated Hair Styling Tool For Home Use, Salon, Hair Salon, Mother's Day Gift',
                                                                                                                                     '1pc Mini Bag Sealer, Rechargeable Portable Sealing Machine, Handheld Plastic Vacuum Sealer For Kitchen Packaging',
 ...
                                                                                                                  'WhizMax 14000 BTU Dual Hose Portable Air Conditioner And Heater - Dehumidifier, Fan - For Rooms Up To 700 Sq. Ft - AC Unit + Heater',
                                                                                                              'Healthy Ceramic Nonstick, 12" 5QT Square Electric Skillet With Glass Lid, Dishwasher Safe, Adjustable Temperature Control, PFAS-, Black',
                                                                                  'BOSSCARE 3D Full Body SL Track Massage Chair, APP Control, Body Scanning, Zero Gravity Shiatsu Massaging Recliner, Heating Therapy, Space-Saving, Bluetooth Speaker',
                                                                                                                                                                             'Unbeatablesale 12 X 24 X 1 In. Fiberglass 4 MERV Air Filter - Pack Of 12',
                                                                                             'Artist Hand Full Body Massage Chair - SL Track Zero Gravity Recliner With 12 Modes, Bluetooth, Body Scan, Foot Roller, Airbags Massage, AI Voice Control',
                                                                                                                                                                                                             'Unbeatablesale 142Mhz .25 Wave Kulduckie',
                                                                                                                                                                                                   'Unbeatablesale 440-460Mhz Load And Tip Only -Black',
                                                                                                                                              'TaoTronics Air Fryer, 1700W 14.8 QT, 9 In 1 Air Fryer Oven, Oil-Less Cooker With Rotisserie Shaft AF010',
                                                                                                                                         'Air Fryer 5.3 Quart, Digital Oilless Frying Cooker, Auto Shut Off, Stainless Steel, 8 Preset Programs, 1700W',
                                                             'Up To 350lbs Okin Motor Power Lift Recliner Chair For Elderly, Heavy Duty Motion Mechanism With 8-Point Vibration Massage And Lumbar Heating, Two Cup Holders And USB Charge Port, Brown']
Length: 3591, dtype: str

In [11]:
df['goods-title-link']= df['goods-title-link'].drop_duplicates()

In [12]:
df['goods-title-link'].shape

(3986,)

In [13]:


df= df.drop_duplicates()

In [14]:
df.shape

(3861, 8)

In [15]:
df['goods-title-link']= df['goods-title-link'].str.strip('unwanted_data')

In [16]:
df['goods-title-link'].isnull().sum()

np.int64(271)

In [17]:
df['goods-title-link']= df['goods-title-link'].ffill()

In [34]:
df.head()

,goods-title-link--jump,goods-title-link--jump href,rank-title,rank-sub,price,discount,selling_proposition,goods-title-link
0,1pc Rechargeable Deep Tissue Muscle Handheld M...,https://us.shein.com/1pc-Rechargeable-Deep-Tis...,#1 Best Sellers,in Give Gifts,$2.03,-22%,Recently Not Sell,Link NOt Available
1,1pc Portable Hanging Neck Fan,https://us.shein.com/1pc-Portable-Hanging-Neck...,#4 Best Sellers,in Top rated in Portable Fans,$6.48,-20%,Recently Not Sell,Link NOt Available
2,1pc Pink Colored Curved Eyelash Curler False E...,https://us.shein.com/1pc-Pink-Colored-Curved-E...,#4 Best Sellers,in Top rated in Portable Fans,$1.80,-20%,400+ sold recently,Link NOt Available
3,1 Mini Portable Handheld Fan With 2 Aa Batteri...,https://us.shein.com/1-Mini-Portable-Handheld-...,#4 Best Sellers,in Top rated in Portable Fans,$0.88,-72%,5.6k+ sold recently,Link NOt Available
4,"Wit Water Flosser,Portable Oral Irrigator With...",https://us.shein.com/Wit-Water-Flosser-Portabl...,#6 Best Sellers,in Oral Irrigators,$12.06,-40%,Recently Not Sell,Link NOt Available

In [19]:
df['goods-title-link']= df['goods-title-link'].fillna('Link NOt Available')

In [20]:
df.isnull().sum()

goods-title-link--jump         3821
goods-title-link--jump href    3821
rank-title                     3302
rank-sub                       3302
price                             0
discount                       1524
selling_proposition            2503
goods-title-link                  0
dtype: int64

In [21]:
df['discount']= df['discount'].ffill()

In [22]:
df.isnull().sum()

goods-title-link--jump         3821
goods-title-link--jump href    3821
rank-title                     3302
rank-sub                       3302
price                             0
discount                          0
selling_proposition            2503
goods-title-link                  0
dtype: int64

In [23]:
df['selling_proposition']=df['selling_proposition'].fillna('Recently Not Sell')

In [24]:
df['goods-title-link--jump href']= df['goods-title-link--jump href'].fillna('Link Not Available')

In [25]:
df['goods-title-link--jump']=df['goods-title-link--jump'].fillna('Data Not Availabe')

In [27]:
df.isnull().sum()

goods-title-link--jump            0
goods-title-link--jump href       0
rank-title                     3302
rank-sub                       3302
price                             0
discount                          0
selling_proposition               0
goods-title-link                  0
dtype: int64

In [29]:
df['rank-title']= df['rank-title'].ffill()

In [32]:
df.isnull().sum()

goods-title-link--jump         0
goods-title-link--jump href    0
rank-title                     0
rank-sub                       0
price                          0
discount                       0
selling_proposition            0
goods-title-link               0
dtype: int64

In [35]:
df['discount'].unique()

<ArrowStringArray>
['-22%', '-20%', '-72%', '-40%', '-41%',  '-5%', '-35%', '-55%', '-63%',
 '-28%', '-53%', '-11%', '-50%', '-47%', '-29%', '-13%', '-48%',  '-4%',
 '-32%', '-25%', '-51%', '-46%', '-16%', '-54%', '-44%', '-15%', '-27%',
 '-71%', '-10%', '-17%',  '-7%', '-30%', '-60%', '-18%', '-37%', '-49%',
 '-69%', '-52%',  '-3%', '-21%', '-34%', '-70%',  '-2%',  '-8%', '-36%',
 '-61%',  '-1%', '-14%', '-58%',  '-6%', '-38%', '-19%', '-31%', '-12%',
 '-39%', '-26%', '-67%', '-33%', '-23%', '-43%', '-64%', '-65%', '-59%',
 '-45%', '-56%', '-62%', '-24%',  '-9%', '-85%', '-77%', '-68%', '-42%',
 '-75%', '-66%', '-74%', '-57%', '-73%', '-80%', '-88%', '-76%']
Length: 80, dtype: str

In [36]:
df.info()

<class 'pandas.DataFrame'>
Index: 3861 entries, 0 to 3985
Data columns (total 8 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   goods-title-link--jump       3861 non-null   str
 1   goods-title-link--jump href  3861 non-null   str
 2   rank-title                   3861 non-null   str
 3   rank-sub                     3861 non-null   str
 4   price                        3861 non-null   str
 5   discount                     3861 non-null   str
 6   selling_proposition          3861 non-null   str
 7   goods-title-link             3861 non-null   str
dtypes: str(8)
memory usage: 1.2 MB

In [42]:
price= {'price':'price($)'}
df.rename(columns=price,inplace=True)

In [49]:
df['price($)'] = (
    df['price($)']
    .str.replace(',', '')
    .str.replace('$', '')
)

df['price($)'] = pd.to_numeric(df['price($)'], errors='coerce')

In [53]:
df['discount']= (
               df['discount']
               .str.replace('-','')
               .str.replace('%','')
)
df['discount']=pd.to_numeric(df['discount'],errors='coerce')

In [55]:
df.isnull()

,goods-title-link--jump,goods-title-link--jump href,rank-title,rank-sub,price($),discount,selling_proposition,goods-title-link
0,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...
3981,False,False,False,False,False,False,False,False
3982,False,False,False,False,False,False,False,False
3983,False,False,False,False,False,False,False,False
3984,False,False,False,False,False,False,False,False
3985,False,False,False,False,False,False,False,False

In [58]:
df.to_csv('cleaned_appliances.csv')